tpm2_control/Makefile: fixed linking order of libaries
Fixes following linker errors when build on debian bookworm:
  cc -std=gnu99 -I.. -I../include -I../tpm2d -Icommon -pedantic -O2 -Wall -Wextra -Wformat -Wformat-security -fstack-protector-all -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -fpic -pie -Wcast-align -ggdb -DDEBUG_BUILD -Werror -DDEFAULT_BASE_PATH=\"/var/lib/cml\" -DLOGFILE_PATH=\"/var/log\" attestation.pb-c.c tpm2d.pb-c.c tpm2d_control.c -lc -lprotobuf-c -lprotobuf-c-text -Lcommon -lcommon_full -o tpm2_control
  /usr/bin/ld: common/libcommon_full.a(protobuf-text.o): in function `protobuf_message_new_from_textfile':
  [..]/common/protobuf-text.c:75: undefined reference to `protobuf_c_text_from_file'
  /usr/bin/ld: common/libcommon_full.a(protobuf-text.o): in function `protobuf_message_new_from_string':
  /home/weiss/cml/common/protobuf-text.c:104: undefined reference to `protobuf_c_text_from_string'
  /usr/bin/ld: [..]/common/protobuf-text.c:121: undefined reference to `protobuf_c_text_free_ProtobufCTextError_data'
  /usr/bin/ld: [..]/common/protobuf-text.c:116: undefined reference to `protobuf_c_text_free_ProtobufCTextError_data'
  /usr/bin/ld: [..]/common/protobuf-text.c:109: undefined reference to `protobuf_c_text_free_ProtobufCTextError_data'
  /usr/bin/ld: common/libcommon_full.a(protobuf-text.o): in function `protobuf_string_from_message':
  [..]/common/protobuf-text.c:174: undefined reference to `protobuf_c_text_to_string'
  collect2: error: ld returned 1 exit status
  make: *** [Makefile:76: tpm2_control] Error 1

Fixes: e3290781c638 ("tpm2_control/Makefile: link libcommon_full")
Signed-off-by: Michael Weiß <michael.weiss@aisec.fraunhofer.de>