daemon: added missing include linux/seccomp.h
Building the 'cmld' in buildroot results in the following compiler error:
  c_seccomp/seccomp.c:418:31: error: 'SECCOMP_USER_NOTIF_FLAG_CONTINUE' undeclared.
Just include the missing header 'linux/seccomp.h' to fix this issue.

Fixes: 84b9064405fe ("dameon/c_seccomp: Moved c_seccomp.c to c_seccomp/seccomp.c")
Signed-off-by: Simon Ott <simon.ott@aisec.fraunhofer.de>
[ michael.weiss ] added commit description and fixes tag
Signed-off-by: Michael Weiß <michael.weiss@aisec.fraunhofer.de>