daemon/u_perm: Fixed warning in u_perm_start_child_early()
In u_perm_start_child_early() the variable d is used as alias for
elements of the static device_rule array unit_dev_whitelist[].
The corresponding struct device_rule d contains only constant strings
in d.dst. However if compiling with sanitizers enabled this leads
to a false positive for the overflow check in the format string.
Thus, we just ASSERT(d.dst) to make sanitizers happy.

Fixes following warning if compiling with sanitizers:

  In file included from common/macro.h:47,
                   from u_perm.c:35:
  u_perm.c: In function ‘u_perm_start_child_early’:
  u_perm.c:201:23: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
    201 |                 DEBUG("mknod (%d:%d) at %s done", d.major, d.minor, d.dst);
        |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
  common/logf.h:171:70: note: in definition of macro ‘logf_message_guard’
    171 |                         logf_message_file(level, __FILE__, __LINE__, __VA_ARGS__);                 \
        |                                                                      ^~~~~~~~~~~
  common/macro.h:68:20: note: in expansion of macro ‘logf_debug’
     68 | #define DEBUG(...) logf_debug(__VA_ARGS__) //!< Debug logging (enabled only in debug builds).
        |                    ^~~~~~~~~~
  u_perm.c:201:17: note: in expansion of macro ‘DEBUG’
    201 |                 DEBUG("mknod (%d:%d) at %s done", d.major, d.minor, d.dst);
        |                 ^~~~~
  u_perm.c:201:41: note: format string is defined here
    201 |                 DEBUG("mknod (%d:%d) at %s done", d.major, d.minor, d.dst);
        |                                         ^~

Signed-off-by: Michael Weiß <michael.weiss@aisec.fraunhofer.de>